In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv('cleaned.csv')

In [3]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [4]:
df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [5]:
df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski"

In [18]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [24]:
# converting same words in one like dancing,danced,dance into danc
def stem(text):
    y=[]

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [25]:
df['tags']=df['tags'].apply(stem)

In [26]:
# converting into vectors
from sklearn.feature_extraction.text import CountVectorizer
import nltk
cv = CountVectorizer(max_features=5000,stop_words='english')

In [27]:
vectors = cv.fit_transform(df['tags']).toarray()

In [28]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [30]:
pd.DataFrame(cv.get_feature_names_out())

                   0
0                000
1                007
2                 10
3                100
4                 11
...              ...
4995  zombieapocalyp
4996         zombies
4997            zone
4998             zoo
4999  zooeydeschanel

[5000 rows x 1 columns]

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

In [46]:
# calculating distances
similarity = cosine_similarity(vectors)

In [37]:
similarity[0]

array([1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
       0.        ], shape=(4806,))

In [38]:
def recommend(movie):
    movie_index = df[df['title']== movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse = True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(df.iloc[i[0]].title)

In [40]:
recommend('Avatar')

Aliens vs Predator: Requiem
Falcon Rising
Independence Day
Titan A.E.
Aliens

In [41]:
import pickle

In [42]:
pickle.dump(df,open('movies.pkl','wb'))

In [43]:
pickle.dump(df.to_dict(),open('movies_dict.pkl','wb'))

In [49]:
pickle.dump(similarity,open('similarity.pkl','wb'))